/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utama;
import bayarzakat.form_emas;
import bayarzakat.form_penghasilan;
import bayarzakat.form_tabungan;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import database.KasZakat;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class utama extends javax.swing.JFrame {

    /**
     * Creates new form utama
     */
    private Connection conn = new KasZakat().getKasZakat();
    public utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        bodypanel = new javax.swing.JPanel();
        menupanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homebtn = new javax.swing.JButton();
        transferbtn = new javax.swing.JButton();
        hitungbtn = new javax.swing.JButton();
        LogOutbtn = new javax.swing.JButton();
        mainpanel = new javax.swing.JPanel();
        homepanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ZakatEmas = new javax.swing.JLabel();
        ZakatPenghasilan = new javax.swing.JLabel();
        ZakatTabungan = new javax.swing.JLabel();
        transferpanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JumlahZakat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Combo_masjid = new javax.swing.JComboBox<>();
        Tfmasjid = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jTextField3 = new javax.swing.JTextField();
        hitungpanel = new javax.swing.JPanel();
        bodyhitungpanel = new javax.swing.JPanel();
        pilihhitungpanel = new javax.swing.JPanel();
        pilihemas = new javax.swing.JButton();
        pilihpenghasilan = new javax.swing.JButton();
        pilihtabungan = new javax.swing.JButton();
        hitungzakatpanel = new javax.swing.JPanel();
        Mainhitungpanel = new javax.swing.JPanel();
        HitungEmasPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        HitungPenghasilanPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        HitungTabunganPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jToggleButton2.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jToggleButton2.setIcon(new javax.swing.ImageIcon("C:\\TUBES PBO\\img\\hom.png")); // NOI18N
        jToggleButton2.setText("Home");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton5.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jToggleButton5.setIcon(new javax.swing.ImageIcon("C:\\TUBES PBO\\img\\hom.png")); // NOI18N
        jToggleButton5.setText("Home");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setResizable(false);

        bodypanel.setBackground(new java.awt.Color(255, 255, 255));
        bodypanel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        menupanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\TUBES PBO\\img\\logo_e_zakat_main-removebg-preview.png")); // NOI18N
        jLabel1.setText("jLabel1");

        homebtn.setBackground(new java.awt.Color(51, 204, 0));
        homebtn.setFont(new java.awt.Font("Segoe UI Emoji", 0, 13)); // NOI18N
        homebtn.setIcon(new javax.swing.ImageIcon("C:\\TUBES PBO\\img\\hom.png")); // NOI18N
        homebtn.setText("Home");
        homebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        homebtn.setBorderPainted(false);
        homebtn.setIconTextGap(10);
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        transferbtn.setBackground(new java.awt.Color(51, 204, 0));
        transferbtn.setFont(new java.awt.Font("Segoe UI Emoji", 0, 13)); // NOI18N
        transferbtn.setIcon(new javax.swing.ImageIcon("C:\\TUBES PBO\\img\\transfer.png")); // NOI18N
        transferbtn.setText("Transfer");
        transferbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        transferbtn.setBorderPainted(false);
        transferbtn.setIconTextGap(10);
        transferbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferbtnActionPerformed(evt);
            }
        });

        hitungbtn.setBackground(new java.awt.Color(51, 204, 0));
        hitungbtn.setFont(new java.awt.Font("Segoe UI Emoji", 0, 13)); // NOI18N
        hitungbtn.setIcon(new javax.swing.ImageIcon("C:\\TUBES PBO\\img\\hom.png")); // NOI18N
        hitungbtn.setText("Hitung Zakat");
        hitungbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hitungbtn.setBorderPainted(false);
        hitungbtn.setIconTextGap(10);
        hitungbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungbtnActionPerformed(evt);
            }
        });

        LogOutbtn.setBackground(new java.awt.Color(51, 204, 0));
        LogOutbtn.setFont(new java.awt.Font("Segoe UI Emoji", 0, 13)); // NOI18N
        LogOutbtn.setIcon(new javax.swing.ImageIcon("C:\\TUBES PBO\\img\\log out.png")); // NOI18N
        LogOutbtn.setText("Log Out");
        LogOutbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogOutbtn.setBorderPainted(false);
        LogOutbtn.setIconTextGap(10);
        LogOutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transferbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hitungbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(LogOutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(homebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transferbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hitungbtn)
                .addGap(18, 18, 18)
                .addComponent(LogOutbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainpanel.setBackground(new java.awt.Color(223, 255, 213));
        mainpanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainpanel.setLayout(new java.awt.CardLayout());

        homepanel.setBackground(new java.awt.Color(223, 255, 213));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel2.setText("Tunaikan Zakat Anda Sekarang !");

        ZakatEmas.setIcon(new javax.swing.ImageIcon("C:\\TUBES PBO\\img\\emass.png")); // NOI18N
        ZakatEmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZakatEmasMouseClicked(evt);
            }
        });

        ZakatPenghasilan.setIcon(new javax.swing.ImageIcon("C:\\TUBES PBO\\img\\penghasilan.png")); // NOI18N
        ZakatPenghasilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZakatPenghasilanMouseClicked(evt);
            }
        });

        ZakatTabungan.setIcon(new javax.swing.ImageIcon("C:\\TUBES PBO\\img\\tabungan.png")); // NOI18N
        ZakatTabungan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZakatTabunganMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout homepanelLayout = new javax.swing.GroupLayout(homepanel);
        homepanel.setLayout(homepanelLayout);
        homepanelLayout.setHorizontalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ZakatEmas)
                .addGap(34, 34, 34)
                .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addComponent(ZakatPenghasilan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ZakatTabungan)
                        .addGap(26, 26, 26))
                    .addGroup(homepanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(272, Short.MAX_VALUE))))
        );
        homepanelLayout.setVerticalGroup(
            homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel2)
                .addGap(70, 70, 70)
                .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ZakatEmas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ZakatPenghasilan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(ZakatTabungan))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        mainpanel.add(homepanel, "card6");

        transferpanel.setBackground(new java.awt.Color(223, 255, 213));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel7.setText("Transfer Untuk Masjid");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Jumlah Zakat");

        JumlahZakat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JumlahZakatKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Pilih Masjid");

        Combo_masjid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masjid Aljabal nur", "Masjid At-Taubah" }));
        Combo_masjid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_masjidActionPerformed(evt);
            }
        });

        Tfmasjid.setBackground(new java.awt.Color(51, 102, 255));
        Tfmasjid.setForeground(new java.awt.Color(255, 255, 255));
        Tfmasjid.setText("Transfer");
        Tfmasjid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfmasjidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(JumlahZakat, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Combo_masjid, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addComponent(Tfmasjid, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JumlahZakat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Combo_masjid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Tfmasjid, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addGap(31, 31, 31))))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel10.setText("Transfer Untuk Perorangan");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Jumlah Zakat");

        jTextField2.setText("Jumlah Zakat yang ditransfer");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Nama Penerima");

        jToggleButton3.setBackground(new java.awt.Color(51, 102, 255));
        jToggleButton3.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton3.setText("Transfer");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jTextField3.setText("Nama Penerima");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addContainerGap(304, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout transferpanelLayout = new javax.swing.GroupLayout(transferpanel);
        transferpanel.setLayout(transferpanelLayout);
        transferpanelLayout.setHorizontalGroup(
            transferpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferpanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(transferpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        transferpanelLayout.setVerticalGroup(
            transferpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferpanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainpanel.add(transferpanel, "card3");

        hitungpanel.setBackground(new java.awt.Color(223, 255, 213));

        bodyhitungpanel.setBackground(new java.awt.Color(255, 102, 102));

        pilihhitungpanel.setBackground(new java.awt.Color(255, 255, 255));

        pilihemas.setIcon(new javax.swing.ImageIcon("C:\\TUBES PBO\\img\\hitungemas.png")); // NOI18N
        pilihemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihemasActionPerformed(evt);
            }
        });

        pilihpenghasilan.setIcon(new javax.swing.ImageIcon("C:\\TUBES PBO\\img\\hitungpenghasilan.png")); // NOI18N
        pilihpenghasilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihpenghasilanActionPerformed(evt);
            }
        });

        pilihtabungan.setIcon(new javax.swing.ImageIcon("C:\\TUBES PBO\\img\\hitungtabungan.png")); // NOI18N
        pilihtabungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihtabunganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pilihhitungpanelLayout = new javax.swing.GroupLayout(pilihhitungpanel);
        pilihhitungpanel.setLayout(pilihhitungpanelLayout);
        pilihhitungpanelLayout.setHorizontalGroup(
            pilihhitungpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pilihhitungpanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(pilihemas)
                .addGap(93, 93, 93)
                .addComponent(pilihpenghasilan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pilihtabungan)
                .addGap(67, 67, 67))
        );
        pilihhitungpanelLayout.setVerticalGroup(
            pilihhitungpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pilihhitungpanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pilihhitungpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pilihemas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pilihpenghasilan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pilihtabungan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        Mainhitungpanel.setBackground(new java.awt.Color(255, 255, 255));
        Mainhitungpanel.setLayout(new java.awt.CardLayout());

        HitungEmasPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel3.setText("Hitung Emas");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Jumlah Emas (per gram)");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Note:\n- Perhitungan zakat diupdate otomatis berdasarkan update harga emas\n- Harga emas per gram saat ini Rp921.528 (www.harga-emas.org)\n- Nishab 85 gram per Tahun Rp78.329.880");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel13.setText("total");

        jButton1.setText("Hitung");

        javax.swing.GroupLayout HitungEmasPanelLayout = new javax.swing.GroupLayout(HitungEmasPanel);
        HitungEmasPanel.setLayout(HitungEmasPanelLayout);
        HitungEmasPanelLayout.setHorizontalGroup(
            HitungEmasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HitungEmasPanelLayout.createSequentialGroup()
                .addGroup(HitungEmasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HitungEmasPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(HitungEmasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(HitungEmasPanelLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButton1))
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(HitungEmasPanelLayout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel13)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        HitungEmasPanelLayout.setVerticalGroup(
            HitungEmasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HitungEmasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HitungEmasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        Mainhitungpanel.add(HitungEmasPanel, "card2");

        HitungPenghasilanPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel14.setText("Hitung Penghasilan");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("Pendapatan (per bulan)");

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Note:\n- Perhitungan zakat diupdate otomatis berdasarkan update harga emas\n- Harga emas per gram saat ini Rp921.528 (www.harga-emas.org)\n- Nishab 85 gram per Bulan Rp6.527.490\n- Dianjurkan dipotong dari gaji bruto");
        jScrollPane2.setViewportView(jTextArea2);

        jButton2.setText("Hitung");

        jLabel4.setText("Total");

        javax.swing.GroupLayout HitungPenghasilanPanelLayout = new javax.swing.GroupLayout(HitungPenghasilanPanel);
        HitungPenghasilanPanel.setLayout(HitungPenghasilanPanelLayout);
        HitungPenghasilanPanelLayout.setHorizontalGroup(
            HitungPenghasilanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HitungPenghasilanPanelLayout.createSequentialGroup()
                .addGroup(HitungPenghasilanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HitungPenghasilanPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(HitungPenghasilanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HitungPenghasilanPanelLayout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(HitungPenghasilanPanelLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel4)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        HitungPenghasilanPanelLayout.setVerticalGroup(
            HitungPenghasilanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HitungPenghasilanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HitungPenghasilanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        Mainhitungpanel.add(HitungPenghasilanPanel, "card3");

        HitungTabunganPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel16.setText("Hitung Tabungan");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("Saldo Tabungan");
        jLabel17.setIconTextGap(7);

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("Note:\n- Perhitungan zakat diupdate otomatis berdasarkan update harga emas\n- Harga emas per gram saat ini Rp921.528 (www.harga-emas.org)\n- Nishab 85 gram per Tahun Rp78.329.880");
        jScrollPane3.setViewportView(jTextArea3);

        jButton3.setText("Hitung");

        jLabel5.setText("label");

        javax.swing.GroupLayout HitungTabunganPanelLayout = new javax.swing.GroupLayout(HitungTabunganPanel);
        HitungTabunganPanel.setLayout(HitungTabunganPanelLayout);
        HitungTabunganPanelLayout.setHorizontalGroup(
            HitungTabunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HitungTabunganPanelLayout.createSequentialGroup()
                .addGroup(HitungTabunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HitungTabunganPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(HitungTabunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HitungTabunganPanelLayout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(HitungTabunganPanelLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel5)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        HitungTabunganPanelLayout.setVerticalGroup(
            HitungTabunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HitungTabunganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HitungTabunganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(35, 35, 35))
        );

        Mainhitungpanel.add(HitungTabunganPanel, "card4");

        javax.swing.GroupLayout hitungzakatpanelLayout = new javax.swing.GroupLayout(hitungzakatpanel);
        hitungzakatpanel.setLayout(hitungzakatpanelLayout);
        hitungzakatpanelLayout.setHorizontalGroup(
            hitungzakatpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mainhitungpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        hitungzakatpanelLayout.setVerticalGroup(
            hitungzakatpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mainhitungpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bodyhitungpanelLayout = new javax.swing.GroupLayout(bodyhitungpanel);
        bodyhitungpanel.setLayout(bodyhitungpanelLayout);
        bodyhitungpanelLayout.setHorizontalGroup(
            bodyhitungpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyhitungpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyhitungpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pilihhitungpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hitungzakatpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bodyhitungpanelLayout.setVerticalGroup(
            bodyhitungpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyhitungpanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pilihhitungpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(hitungzakatpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout hitungpanelLayout = new javax.swing.GroupLayout(hitungpanel);
        hitungpanel.setLayout(hitungpanelLayout);
        hitungpanelLayout.setHorizontalGroup(
            hitungpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hitungpanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(bodyhitungpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        hitungpanelLayout.setVerticalGroup(
            hitungpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hitungpanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(bodyhitungpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        mainpanel.add(hitungpanel, "card4");

        javax.swing.GroupLayout bodypanelLayout = new javax.swing.GroupLayout(bodypanel);
        bodypanel.setLayout(bodypanelLayout);
        bodypanelLayout.setHorizontalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodypanelLayout.createSequentialGroup()
                .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodypanelLayout.setVerticalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menupanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void TfmasjidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfmasjidActionPerformed
        // TODO add your handling code here:
        String sql = "insert into masjid values (?,?)";
                try{
                    PreparedStatement stat = conn.prepareStatement(sql);
                    stat.setString(1, JumlahZakat.getText());
                    String Masjid = Combo_masjid.getSelectedItem().toString();
                    stat.setString(2, Masjid);
                    
                    
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Donasi Berhasil !");
                }catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Donasi Gagal !" +e);
                }
    }//GEN-LAST:event_TfmasjidActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        // TODO add your handling code here:
        //remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // add panel
        mainpanel.add(homepanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_homebtnActionPerformed

    private void transferbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferbtnActionPerformed
        // TODO add your handling code here:
        //remove panel
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // add panel
        mainpanel.add(transferpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_transferbtnActionPerformed

    private void ZakatEmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZakatEmasMouseClicked
        // TODO add your handling code here:
        form_emas start = new form_emas();
        start.setVisible(true);
    }//GEN-LAST:event_ZakatEmasMouseClicked

    private void Combo_masjidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_masjidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_masjidActionPerformed

    private void ZakatPenghasilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZakatPenghasilanMouseClicked
        // TODO add your handling code here:
        form_penghasilan start = new form_penghasilan();
        start.setVisible(true);
    }//GEN-LAST:event_ZakatPenghasilanMouseClicked

    private void ZakatTabunganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZakatTabunganMouseClicked
        // TODO add your handling code here:
        form_tabungan start = new form_tabungan();
        start.setVisible(true);
    }//GEN-LAST:event_ZakatTabunganMouseClicked

    private void LogOutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutbtnActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin ingin keluar ?", "PERHATIAN", dialogBtn);
        
        if (dialogResult == 0){
            System.exit(0);
           
        }
        
    }//GEN-LAST:event_LogOutbtnActionPerformed

    private void JumlahZakatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JumlahZakatKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();       
        if(!Character.isDigit(c)){
            evt.consume();
        }
         
    }//GEN-LAST:event_JumlahZakatKeyTyped

    private void pilihemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihemasActionPerformed
        // TODO add your handling code here:
        Mainhitungpanel.removeAll();
        Mainhitungpanel.repaint();
        Mainhitungpanel.revalidate();
        // add panel
        Mainhitungpanel.add(HitungEmasPanel);
        Mainhitungpanel.repaint();
        Mainhitungpanel.revalidate();
    }//GEN-LAST:event_pilihemasActionPerformed

    private void hitungbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungbtnActionPerformed
        // TODO add your handling code here:
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        // add panel
        mainpanel.add(hitungpanel);
        mainpanel.repaint();
        mainpanel.revalidate();
        
    }//GEN-LAST:event_hitungbtnActionPerformed

    private void pilihpenghasilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihpenghasilanActionPerformed
        // TODO add your handling code here:
        Mainhitungpanel.removeAll();
        Mainhitungpanel.repaint();
        Mainhitungpanel.revalidate();
        // add panel
        Mainhitungpanel.add(HitungPenghasilanPanel);
        Mainhitungpanel.repaint();
        Mainhitungpanel.revalidate();
        
    }//GEN-LAST:event_pilihpenghasilanActionPerformed

    private void pilihtabunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihtabunganActionPerformed
        // TODO add your handling code here:
        Mainhitungpanel.removeAll();
        Mainhitungpanel.repaint();
        Mainhitungpanel.revalidate();
        // add panel
        Mainhitungpanel.add(HitungTabunganPanel);
        Mainhitungpanel.repaint();
        Mainhitungpanel.revalidate();
    }//GEN-LAST:event_pilihtabunganActionPerformed

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
                char c = evt.getKeyChar();       
        if(!Character.isDigit(c)){
            evt.consume();
        }
         
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
                char c = evt.getKeyChar();       
        if(!Character.isDigit(c)){
            evt.consume();
        }
         
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
                char c = evt.getKeyChar();       
        if(!Character.isDigit(c)){
            evt.consume();
        }
         
    }//GEN-LAST:event_jTextField1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combo_masjid;
    private javax.swing.JPanel HitungEmasPanel;
    private javax.swing.JPanel HitungPenghasilanPanel;
    private javax.swing.JPanel HitungTabunganPanel;
    private javax.swing.JTextField JumlahZakat;
    private javax.swing.JButton LogOutbtn;
    private javax.swing.JPanel Mainhitungpanel;
    private javax.swing.JToggleButton Tfmasjid;
    private javax.swing.JLabel ZakatEmas;
    private javax.swing.JLabel ZakatPenghasilan;
    private javax.swing.JLabel ZakatTabungan;
    private javax.swing.JPanel bodyhitungpanel;
    private javax.swing.JPanel bodypanel;
    private javax.swing.JButton hitungbtn;
    private javax.swing.JPanel hitungpanel;
    private javax.swing.JPanel hitungzakatpanel;
    private javax.swing.JButton homebtn;
    private javax.swing.JPanel homepanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel menupanel;
    private javax.swing.JButton pilihemas;
    private javax.swing.JPanel pilihhitungpanel;
    private javax.swing.JButton pilihpenghasilan;
    private javax.swing.JButton pilihtabungan;
    private javax.swing.JButton transferbtn;
    private javax.swing.JPanel transferpanel;
    // End of variables declaration//GEN-END:variables
}
